### ISSUE TITLE
关于9.0版本的监控技能的适配

### ISSUE THREAD

**Issue by q513902026** [q513902026/ClassMods#2]
如果你有对9.0版本监控技能有相关的想法
都可以在这个issues中提出 我会在实验过后添加相关代码

**Comment by xiong955** [comment]
最新版的圣骑士聊天框会输出技能的ID

**Comment by q513902026** [comment]
已经修复 
其次 存在的问题请新开issues

**Comment by xiong955** [comment]
谢谢,ok



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HopeAsd"<notifications@github.com&gt;; 
发送时间: 2020年10月25日(星期天) 晚上10:16
收件人: "q513902026/ClassMods"<ClassMods@noreply.github.com&gt;; 
抄送: "Paladin。"<xiong955@vip.qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [q513902026/ClassMods] 关于9.0版本的监控技能的适配 (#2)





 
已经修复
 其次 存在的问题请新开issues
